/** Chữ hiển thị của tab Cài đặt (settings-page.ts). Bản tiếng Anh phải đủ khoá như tiếng Việt. */
const vi = {
  title: 'Cài đặt',
  navAccount: 'Tài khoản', navPasswords: 'Mật khẩu', navAppearance: 'Giao diện', navStartup: 'Khởi động', navAbout: 'Giới thiệu',
  accountHint: 'Tài khoản Vala Desktop của bạn: dùng để mở các ứng dụng của đơn vị, giữ phiên các hệ thống nguồn và gửi cho Vala lấy dữ liệu thay bạn.',
  notSignedIn: 'Chưa đăng nhập.', signIn: 'Đăng nhập', signedInAs: 'Đã đăng nhập', serverIs: 'Máy chủ',
  openPortal: 'Mở cổng báo cáo', logout: 'Đăng xuất',
  pwHint: 'Mật khẩu các hệ thống (eGov, eTask, QLVB…) được mã hoá bằng kho mật khẩu của hệ điều hành trên máy này, chỉ dùng để Vala Desktop tự đăng nhập lại đúng hệ thống đó, không gửi lên máy chủ Vala.',
  pwUnavailable: 'Máy này chưa có kho mật khẩu của hệ điều hành — không lưu được mật khẩu.',
  pwSources: 'Hệ thống nguồn', pwSites: 'Trang khác', pwNever: 'Không bao giờ lưu',
  pwSourcesSignedOut: 'Đăng nhập để thấy các hệ thống nguồn của bạn.',
  ssoPassword: 'SSO của đơn vị — dùng chung cho mọi ứng dụng',
  pwNoSites: 'Chưa lưu mật khẩu cho trang nào khác. Đăng nhập một trang trong ứng dụng, Vala Desktop sẽ hỏi lưu.',
  pwNotSaved: 'Chưa lưu mật khẩu', pwSavedAt: 'Lưu lúc', pwAuto: 'Tự đăng nhập lại',
  pwSave: 'Lưu mật khẩu…', pwChange: 'Đổi…', pwDelete: 'Xoá', pwAllow: 'Bỏ khỏi danh sách',
  pwConfirmDelete: 'Xoá mật khẩu đã lưu của',
  langLabel: 'Ngôn ngữ', themeLabel: 'Chế độ màu', themeLight: 'Sáng', themeDark: 'Tối', themeSystem: 'Theo hệ thống',
  autostartLabel: 'Chạy Vala Desktop cùng hệ điều hành, ẩn ở khay hệ thống',
  autostartHint: 'Để Vala Desktop giữ phiên và tự đăng nhập lại ngay khi bật máy. Đóng cửa sổ chỉ ẩn xuống khay; muốn tắt hẳn thì chọn Thoát.',
  autostartDev: 'Bản dev không đăng ký chạy cùng hệ điều hành.',
  aboutVersion: 'Phiên bản', checkUpdate: 'Kiểm tra cập nhật', installUpdate: 'Cập nhật lên bản',
  whatsNewCurrent: 'Có gì mới trong bản này', whatsNewPending: 'Có gì mới trong bản', 
  updateHint: 'Vala Desktop tự kiểm tra bản mới lúc mở và 4 giờ một lần.', noUpdate: 'Bản này không tự cập nhật được (bản dev hoặc bản zip).',
};
const en: typeof vi = {
  title: 'Settings',
  navAccount: 'Account', navPasswords: 'Passwords', navAppearance: 'Appearance', navStartup: 'Startup', navAbout: 'About',
  accountHint: 'Your Vala Desktop account: used to open your organization\'s apps, keep your source-system sessions and send them to Vala to fetch data for you.',
  notSignedIn: 'Not signed in.', signIn: 'Sign in', signedInAs: 'Signed in as', serverIs: 'Server',
  openPortal: 'Open reporting portal', logout: 'Sign out',
  pwHint: 'Passwords for your systems (eGov, eTask, document systems…) are encrypted with the operating system’s password store on this computer, used only so Vala Desktop can sign in to that system again, and never sent to the Vala server.',
  pwUnavailable: 'This computer has no operating-system password store — passwords cannot be saved.',
  pwSources: 'Source systems', pwSites: 'Other sites', pwNever: 'Never saved',
  pwSourcesSignedOut: 'Sign in to see your source systems.',
  ssoPassword: 'Organization SSO — shared by all apps',
  pwNoSites: 'No passwords saved for other sites yet. Sign in to a site inside the app and Vala Desktop will offer to save it.',
  pwNotSaved: 'No saved password', pwSavedAt: 'Saved', pwAuto: 'Sign in again automatically',
  pwSave: 'Save password…', pwChange: 'Change…', pwDelete: 'Delete', pwAllow: 'Remove from list',
  pwConfirmDelete: 'Delete the saved password for',
  langLabel: 'Language', themeLabel: 'Color mode', themeLight: 'Light', themeDark: 'Dark', themeSystem: 'System',
  autostartLabel: 'Start Vala Desktop with the operating system, hidden in the system tray',
  autostartHint: 'So Vala Desktop keeps sessions and signs in again as soon as the computer starts. Closing the window only hides it to the tray; choose Quit to exit.',
  autostartDev: 'The dev build does not register to start with the operating system.',
  aboutVersion: 'Version', checkUpdate: 'Check for updates', installUpdate: 'Update to version',
  whatsNewCurrent: 'What’s new in this version', whatsNewPending: 'What’s new in version', 
  updateHint: 'Vala Desktop checks for a new version when it starts and every 4 hours.', noUpdate: 'This copy cannot update itself (dev or zip build).',
};
export const strings = { vi, en };
