/** Chữ hiển thị của tab Cài đặt (settings-page.ts). Bản tiếng Anh phải đủ khoá như tiếng Việt. */
const vi = {
  title: 'Cài đặt',
  navAccount: 'Tài khoản', navPasswords: 'Mật khẩu', navAppearance: 'Giao diện', navStartup: 'Khởi động & cập nhật', navDownloads: 'Tải xuống', navAbout: 'Giới thiệu',
  accountHint: 'Tài khoản Vala Desktop của bạn: dùng để mở các ứng dụng của đơn vị, giữ phiên các hệ thống nguồn và gửi cho Vala lấy dữ liệu thay bạn.',
  notSignedIn: 'Chưa đăng nhập.', signIn: 'Đăng nhập', signedInAs: 'Đã đăng nhập', serverIs: 'Máy chủ',
  openPortal: 'Mở cổng báo cáo', logout: 'Đăng xuất',
  pwHint: 'Mật khẩu các hệ thống (eGov, eTask, QLVB…) được mã hoá bằng kho mật khẩu của hệ điều hành trên máy này, chỉ dùng để Vala Desktop tự đăng nhập lại đúng hệ thống đó, không gửi lên máy chủ Vala.',
  pwUnavailable: 'Máy này chưa có kho mật khẩu của hệ điều hành — không lưu được mật khẩu.',
  pwSources: 'Hệ thống nguồn', pwSites: 'Trang khác', pwNever: 'Không bao giờ lưu',
  pwSourcesSignedOut: 'Đăng nhập để thấy các hệ thống nguồn của bạn.',
  ssoPassword: 'SSO của đơn vị — dùng chung cho mọi ứng dụng',
  pwNoSites: 'Chưa lưu mật khẩu cho trang nào khác. Đăng nhập một trang trong ứng dụng, Vala Desktop sẽ hỏi lưu.',
  pwNotSaved: 'Chưa lưu mật khẩu', pwSavedAt: 'Lưu lúc', pwAuto: 'Tự đăng nhập lại',
  pwSave: 'Lưu mật khẩu…', pwChange: 'Đổi…', pwDelete: 'Xoá', pwAllow: 'Bỏ khỏi danh sách',
  pwConfirmDelete: 'Xoá mật khẩu đã lưu của',
  langLabel: 'Ngôn ngữ', themeLabel: 'Chế độ màu', themeLight: 'Sáng', themeDark: 'Tối', themeSystem: 'Theo hệ thống',
  autostartLabel: 'Chạy Vala Desktop cùng hệ điều hành, ẩn ở khay hệ thống',
  autostartHint: 'Để Vala Desktop giữ phiên và tự đăng nhập lại ngay khi bật máy. Đóng cửa sổ chỉ ẩn xuống khay; muốn tắt hẳn thì chọn Thoát.',
  autostartDev: 'Bản dev không đăng ký chạy cùng hệ điều hành.',
  autoSaveLabel: 'Tự lưu mật khẩu',
  autoSaveHint: 'Đăng nhập một hệ thống hoặc SSO trong Vala Desktop là mật khẩu được lưu luôn (báo một thông báo), không hỏi. Tắt thì Vala Desktop hỏi trước mỗi lần lưu.',
  askDownloadLabel: 'Hỏi trước khi tải tệp',
  askDownloadHint: 'Bật (mặc định): mỗi lần tải, Vala Desktop mở hộp Tải xuống để bạn chọn Mở, Tải về hay Lưu thành… (chọn nơi lưu). Tắt: tệp tải thẳng vào thư mục Tải về.',
  autoUpdateLabel: 'Tự động cập nhật',
  autoUpdateHint: 'Bản mới tải ngầm và tự cài khi bạn không dùng máy (cửa sổ ẩn xuống khay hoặc máy để không 10 phút), rồi mở lại. Tắt thì Vala Desktop chỉ báo có bản mới để bạn tự bấm Cập nhật. Trên Ubuntu luôn cần bạn bấm vì phải nhập mật khẩu quản trị.',
  errorReportLabel: 'Tự gửi báo lỗi cho Bkav',
  errorReportHint: 'Khi ứng dụng gặp lỗi hoặc bị đóng đột ngột, gửi thông tin kỹ thuật (phiên bản, hệ điều hành, mô tả lỗi) để Bkav sửa. Không gửi nội dung trang, mật khẩu hay cookie.',
  aboutVersion: 'Phiên bản', checkUpdate: 'Kiểm tra cập nhật', installUpdate: 'Cập nhật lên bản',
  whatsNewCurrent: 'Có gì mới trong bản này', whatsNewPending: 'Có gì mới trong bản', 
  updateHint: 'Vala Desktop tự kiểm tra bản mới lúc mở và 4 giờ một lần.', noUpdate: 'Bản này không tự cập nhật được (bản dev hoặc bản zip).',
};
const en: typeof vi = {
  title: 'Settings',
  navAccount: 'Account', navPasswords: 'Passwords', navAppearance: 'Appearance', navStartup: 'Startup & updates', navDownloads: 'Downloads', navAbout: 'About',
  accountHint: 'Your Vala Desktop account: used to open your organization\'s apps, keep your source-system sessions and send them to Vala to fetch data for you.',
  notSignedIn: 'Not signed in.', signIn: 'Sign in', signedInAs: 'Signed in as', serverIs: 'Server',
  openPortal: 'Open reporting portal', logout: 'Sign out',
  pwHint: 'Passwords for your systems (eGov, eTask, document systems…) are encrypted with the operating system’s password store on this computer, used only so Vala Desktop can sign in to that system again, and never sent to the Vala server.',
  pwUnavailable: 'This computer has no operating-system password store — passwords cannot be saved.',
  pwSources: 'Source systems', pwSites: 'Other sites', pwNever: 'Never saved',
  pwSourcesSignedOut: 'Sign in to see your source systems.',
  ssoPassword: 'Organization SSO — shared by all apps',
  pwNoSites: 'No passwords saved for other sites yet. Sign in to a site inside the app and Vala Desktop will offer to save it.',
  pwNotSaved: 'No saved password', pwSavedAt: 'Saved', pwAuto: 'Sign in again automatically',
  pwSave: 'Save password…', pwChange: 'Change…', pwDelete: 'Delete', pwAllow: 'Remove from list',
  pwConfirmDelete: 'Delete the saved password for',
  langLabel: 'Language', themeLabel: 'Color mode', themeLight: 'Light', themeDark: 'Dark', themeSystem: 'System',
  autostartLabel: 'Start Vala Desktop with the operating system, hidden in the system tray',
  autostartHint: 'So Vala Desktop keeps sessions and signs in again as soon as the computer starts. Closing the window only hides it to the tray; choose Quit to exit.',
  autostartDev: 'The dev build does not register to start with the operating system.',
  autoSaveLabel: 'Save passwords automatically',
  autoSaveHint: 'When you sign in to a system or SSO inside Vala Desktop, the password is saved right away (with a notification), without asking. Turned off, Vala Desktop asks before saving.',
  askDownloadLabel: 'Ask before downloading a file',
  askDownloadHint: 'On (default): for each download, Vala Desktop opens the Download box so you choose Open, Download or Save as… (pick a folder). Off: files go straight to your Downloads folder.',
  autoUpdateLabel: 'Update automatically',
  autoUpdateHint: "New versions download in the background and install when you're not using the computer (window hidden to the tray or 10 minutes idle), then reopen. Turned off, Vala Desktop only tells you an update is ready so you click Update yourself. On Ubuntu you always click, because it needs an administrator password.",
  errorReportLabel: 'Send error reports to Bkav automatically',
  errorReportHint: 'When the app hits an error or closes unexpectedly, send technical details (version, operating system, error description) so Bkav can fix it. Page content, passwords and cookies are never sent.',
  aboutVersion: 'Version', checkUpdate: 'Check for updates', installUpdate: 'Update to version',
  whatsNewCurrent: 'What’s new in this version', whatsNewPending: 'What’s new in version', 
  updateHint: 'Vala Desktop checks for a new version when it starts and every 4 hours.', noUpdate: 'This copy cannot update itself (dev or zip build).',
};
export const strings = { vi, en };
